kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-socket
spec:
   
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80          ## Port inside the Pod ##
      nodePort: 65432   ## Expose to port 30080 ##
  selector:
    ## defines which pods are going to be represented by this service ##
    mylabelname: web-socket

  type: NodePort
